package com.example.tmdbclient

object TmdbApiStatusCodes {

    private val map = mapOf(
        1 to "Success",
        2 to "Invalid service: this service does not exist.",
        3 to "Authentication failed: You do not have permissions to access the service.",
        4 to "Invalid format: This service doesn't exist in that format.",
        5 to "Invalid parameters: Your request parameters are incorrect.",
        6 to "Invalid id: The pre-requisite id is invalid or not found.",
        7 to "Invalid API key: You must be granted a valid key.",
        8 to "Duplicate entry: The data you tried to submit already exists.",
        9 to "Service offline: This service is temporarily offline, try again later.",
        10 to "Suspended API key: Access to your account has been suspended, contact TMDB.",
        11 to "Internal error: Something went wrong, contact TMDB.",
        12 to "The item/record was updated successfully.",
        13 to "The item/record was deleted successfully.",
        14 to "Authentication failed.",
        15 to "Failed.",
        16 to "Device denied.",
        17 to "Session denied.",
        18 to "Validation failed.",
        19 to "Invalid accept header.",
        20 to "Invalid date range: Should be a range no longer than 14 days.",
        21 to "Entry not found: The item you are trying to edit cannot be found.",
        22 to "Invalid page: Pages start at 1 and max at 1000. They are expected to be an integer.",
        23 to "Invalid date: Format needs to be YYYY-MM-DD.",
        24 to "Your request to the backend server timed out. Try again.",
        25 to "Your request count (#) is over the allowed limit of (40).",
        26 to "You must provide a username and password.",
        27 to "Too many append to response objects: The maximum number of remote calls is 20.",
        28 to "Invalid timezone: Please consult the documentation for a valid timezone.",
        29 to "You must confirm this action: Please provide a confirm=true parameter.",
        30 to "Invalid username and/or password: You did not provide a valid login.",
        31 to "Account disabled: Your account is no longer active. Contact TMDB if this is an error.",
        32 to "Email not verified: Your email address has not been verified.",
        33 to "Invalid request token: The request token is either expired or invalid.",
        34 to "The resource you requested could not be found.",
        35 to "Invalid token.",
        36 to "This token hasn't been granted write permission by the user.",
        37 to "The requested session could not be found.",
        38 to "You don't have permission to edit this resource.",
        39 to "This resource is private.",
        40 to "Nothing to update.",
        41 to "This request token hasn't been approved by the user.",
        42 to "This request method is not supported for this resource.",
        43 to "Couldn't connect to the backend server.",
        44 to "The ID is invalid.",
        45 to "This user has been suspended.",
        46 to "The API is undergoing maintenance. Try again later.",
        47 to "The input is not valid.",
    )
}